"""
Theme-specific animation profiles
Each theme has unique animations and effects to create distinct UX
"""

THEME_ANIMATIONS = {
    "default": {
        "name": "Default - Smooth & Professional",
        "button_hover_duration": 200,
        "button_hover_curve": "OutCubic",
        "button_press_duration": 100,
        "page_transition": "fade",
        "page_transition_duration": 250,
        "ripple_enabled": True,
        "ripple_duration": 400,
        "glow_effect": False,
        "pulse_effect": False,
        "frost_effect": False,
    },
    "cyberpunk": {
        "name": "Cyberpunk - Fast & Flashy",
        "button_hover_duration": 150,
        "button_hover_curve": "OutQuad",
        "button_press_duration": 80,
        "page_transition": "slide",
        "page_transition_duration": 180,
        "ripple_enabled": True,
        "ripple_duration": 300,
        "glow_effect": True,
        "glow_color": "#FF00FF",
        "glow_intensity": 0.8,
        "pulse_effect": True,
        "pulse_duration": 1200,
        "frost_effect": False,
    },
    "nord": {
        "name": "Nord - Calm & Fluid",
        "button_hover_duration": 250,
        "button_hover_curve": "InOutQuad",
        "button_press_duration": 120,
        "page_transition": "fade",
        "page_transition_duration": 300,
        "ripple_enabled": True,
        "ripple_duration": 500,
        "glow_effect": False,
        "pulse_effect": False,
        "frost_effect": True,
        "frost_shimmer_duration": 2000,
    },
    "dracula": {
        "name": "Dracula - Mysterious & Smooth",
        "button_hover_duration": 220,
        "button_hover_curve": "OutCubic",
        "button_press_duration": 110,
        "page_transition": "fade",
        "page_transition_duration": 280,
        "ripple_enabled": True,
        "ripple_duration": 450,
        "glow_effect": True,
        "glow_color": "#BD93F9",
        "glow_intensity": 0.6,
        "pulse_effect": False,
        "frost_effect": False,
    },
    "ocean": {
        "name": "Ocean - Flowing & Liquid",
        "button_hover_duration": 280,
        "button_hover_curve": "InOutSine",
        "button_press_duration": 130,
        "page_transition": "slide",
        "page_transition_duration": 350,
        "ripple_enabled": True,
        "ripple_duration": 600,
        "glow_effect": False,
        "pulse_effect": False,
        "frost_effect": True,
        "frost_shimmer_duration": 2500,
        "wave_effect": True,
    },
    "sunset": {
        "name": "Sunset - Warm & Gradual",
        "button_hover_duration": 300,
        "button_hover_curve": "InOutQuart",
        "button_press_duration": 140,
        "page_transition": "fade",
        "page_transition_duration": 400,
        "ripple_enabled": True,
        "ripple_duration": 550,
        "glow_effect": True,
        "glow_color": "#FF6B6B",
        "glow_intensity": 0.5,
        "pulse_effect": False,
        "frost_effect": False,
    },
    "forest": {
        "name": "Forest - Natural & Organic",
        "button_hover_duration": 260,
        "button_hover_curve": "OutBack",
        "button_press_duration": 120,
        "page_transition": "fade",
        "page_transition_duration": 320,
        "ripple_enabled": True,
        "ripple_duration": 480,
        "glow_effect": False,
        "pulse_effect": False,
        "frost_effect": False,
        "bounce_effect": True,
    },
    "lavender": {
        "name": "Lavender - Soft & Dreamy",
        "button_hover_duration": 290,
        "button_hover_curve": "InOutSine",
        "button_press_duration": 135,
        "page_transition": "fade",
        "page_transition_duration": 380,
        "ripple_enabled": True,
        "ripple_duration": 520,
        "glow_effect": True,
        "glow_color": "#9C27B0",
        "glow_intensity": 0.4,
        "pulse_effect": True,
        "pulse_duration": 1800,
        "frost_effect": False,
    },
    "cherry": {
        "name": "Cherry - Playful & Vibrant",
        "button_hover_duration": 180,
        "button_hover_curve": "OutBack",
        "button_press_duration": 90,
        "page_transition": "slide",
        "page_transition_duration": 220,
        "ripple_enabled": True,
        "ripple_duration": 350,
        "glow_effect": True,
        "glow_color": "#E91E63",
        "glow_intensity": 0.7,
        "pulse_effect": False,
        "frost_effect": False,
        "bounce_effect": True,
    },
    "midnight": {
        "name": "Midnight - Deep & Elegant",
        "button_hover_duration": 270,
        "button_hover_curve": "InOutCubic",
        "button_press_duration": 125,
        "page_transition": "fade",
        "page_transition_duration": 340,
        "ripple_enabled": True,
        "ripple_duration": 490,
        "glow_effect": True,
        "glow_color": "#3F51B5",
        "glow_intensity": 0.5,
        "pulse_effect": False,
        "frost_effect": True,
        "frost_shimmer_duration": 3000,
    },
    "amber": {
        "name": "Amber - Energetic & Warm",
        "button_hover_duration": 170,
        "button_hover_curve": "OutQuint",
        "button_press_duration": 85,
        "page_transition": "slide",
        "page_transition_duration": 200,
        "ripple_enabled": True,
        "ripple_duration": 320,
        "glow_effect": True,
        "glow_color": "#FF9800",
        "glow_intensity": 0.8,
        "pulse_effect": True,
        "pulse_duration": 1000,
        "frost_effect": False,
    },
    "mint": {
        "name": "Mint - Fresh & Crisp",
        "button_hover_duration": 210,
        "button_hover_curve": "OutCubic",
        "button_press_duration": 105,
        "page_transition": "fade",
        "page_transition_duration": 260,
        "ripple_enabled": True,
        "ripple_duration": 420,
        "glow_effect": False,
        "pulse_effect": False,
        "frost_effect": True,
        "frost_shimmer_duration": 1800,
    },
    "simple": {
        "name": "Simple - Minimal & Direct",
        "button_hover_duration": 150,
        "button_hover_curve": "Linear",
        "button_press_duration": 75,
        "page_transition": "none",
        "page_transition_duration": 0,
        "ripple_enabled": False,
        "ripple_duration": 0,
        "glow_effect": False,
        "pulse_effect": False,
        "frost_effect": False,
        "minimal_mode": True,
    },
    "glassmorphism": {
        "name": "Glassmorphism - Smooth & Translucent",
        "button_hover_duration": 240,
        "button_hover_curve": "InOutSine",
        "button_press_duration": 115,
        "page_transition": "fade",
        "page_transition_duration": 320,
        "ripple_enabled": True,
        "ripple_duration": 500,
        "glow_effect": True,
        "glow_color": "#667eea",
        "glow_intensity": 0.6,
        "pulse_effect": False,
        "frost_effect": True,
        "frost_shimmer_duration": 2200,
        "blur_effect": True,
    },
    "neumorphic": {
        "name": "Neumorphic - Soft & Tactile",
        "button_hover_duration": 200,
        "button_hover_curve": "OutCubic",
        "button_press_duration": 100,
        "page_transition": "fade",
        "page_transition_duration": 280,
        "ripple_enabled": False,
        "ripple_duration": 0,
        "glow_effect": False,
        "pulse_effect": False,
        "frost_effect": False,
        "shadow_effect": True,
        "emboss_effect": True,
    },
}

def get_animation_profile(theme_name):
    """
    Get animation profile for a theme

    Args:
        theme_name: Name of the theme (default, cyberpunk, nord, etc.)

    Returns:
        Dict with animation settings for the theme
    """
    return THEME_ANIMATIONS.get(theme_name, THEME_ANIMATIONS["default"])

def get_easing_curve_enum(curve_name):
    """
    Convert curve name string to Qt easing curve enum

    Args:
        curve_name: Name of easing curve (e.g., "OutCubic", "InOutQuad")

    Returns:
        QEasingCurve.Type enum value
    """
    from PySide6.QtCore import QEasingCurve

    curve_map = {
        "Linear": QEasingCurve.Type.Linear,
        "InQuad": QEasingCurve.Type.InQuad,
        "OutQuad": QEasingCurve.Type.OutQuad,
        "InOutQuad": QEasingCurve.Type.InOutQuad,
        "InCubic": QEasingCurve.Type.InCubic,
        "OutCubic": QEasingCurve.Type.OutCubic,
        "InOutCubic": QEasingCurve.Type.InOutCubic,
        "InQuart": QEasingCurve.Type.InQuart,
        "OutQuart": QEasingCurve.Type.OutQuart,
        "InOutQuart": QEasingCurve.Type.InOutQuart,
        "InQuint": QEasingCurve.Type.InQuint,
        "OutQuint": QEasingCurve.Type.OutQuint,
        "InOutQuint": QEasingCurve.Type.InOutQuint,
        "InSine": QEasingCurve.Type.InSine,
        "OutSine": QEasingCurve.Type.OutSine,
        "InOutSine": QEasingCurve.Type.InOutSine,
        "InBack": QEasingCurve.Type.InBack,
        "OutBack": QEasingCurve.Type.OutBack,
        "InOutBack": QEasingCurve.Type.InOutBack,
    }

    return curve_map.get(curve_name, QEasingCurve.Type.OutCubic)
